import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <Link href="https://github.com/mubeenkh4u/Next-Test">
            <a> my Vercel Hubspot Integration! </a>
          </Link>
        </h1>

        <p className={styles.description}>
          Get started by clicking one of the cards below{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/api/search/crm">
            <a className={styles.card}>
              <h2>Search &rarr;</h2>
              <p>
                Search my hubspot for the random contacts that I have made using
                Fakerjs.
              </p>
            </a>
          </Link>

          <Link href="/api/create/crm">
            <a className={styles.card}>
              <h2>Create a contact on my hubspot space &rarr;</h2>
              <p>Create a contact using this place.</p>
            </a>
          </Link>

          <Link href="/api/batch/crm">
            <a className={styles.card}>
              <h2>Batch Create &rarr;</h2>
              <p>
                Batch create fake contact information using this card, create 10
                at random.
              </p>
            </a>
          </Link>

          <Link href="https://github.com/mubeenkh4u/Next-Test">
            <a className={styles.card}>
              <h2>Source Code &rarr;</h2>
              <p>
                The project is hosted on github, you can browse the code here.
              </p>
            </a>
          </Link>

          <Link href="https://github.com/DrySpell">
            <a className={styles.card}>
              <h2>
                My mentor and friend who helped me with this project. &rarr;
              </h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
